baseURL = "https://happydeathday.ca/"
languageCode = "en-CA"
title = "Happy Death Day"
theme = "blnk"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  post = ["HTML"]
[markup.goldmark.renderer]
  unsafe= true
[params]
  author = "Simon Borer"
  description = "Content to supplement Trampoline Hall lecture"
  mainSections = ["posts"]
  logosvgfile = "world"
  logosvgalt = "Sitting on top of a world"
# [minify]
#   disableCSS = false
#   disableHTML = false
#   disableJS = false
#   disableJSON = false
#   disableSVG = false
#   disableXML = false
#   minifyOutput = false
#   [minify.tdewolff]
#     [minify.tdewolff.css]
#       decimals = -1
#       keepCSS2 = true
#     [minify.tdewolff.html]
#       keepConditionalComments = true
#       keepDefaultAttrVals = true
#       keepDocumentTags = true
#       keepEndTags = true
#       keepWhitespace = false
#     [minify.tdewolff.js]
#     [minify.tdewolff.json]
#     [minify.tdewolff.svg]
#       decimals = -1
#     [minify.tdewolff.xml]
#       keepWhitespace = false