baseURL = "https://happydeathday.ca/"
languageCode = "en-CA"
title = "Happy Death Day"
theme = "blnk"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  post = ["HTML"]
[markup.goldmark.renderer]
  unsafe= true
[params]
  author = "Simon Borer"
  description = "Content to supplement Trampoline Hall lecture"
  mainSections = ["posts"]
  logosvgfile = "grave-raven"
  logosvgalt = "Sitting on top of a world"