[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Content-Security-Policy = "frame-ancestors none;"
  Referrer-Policy = "no-referrer"
  Permissions-Policy = '''
      accelerometer=(self "https://www.youtube-nocookie.com" "https://www.youtube.com"),
      ambient-light-sensor=(),
      autoplay=(self "https://www.youtube-nocookie.com" "https://www.youtube.com"),
      camera=(),
      clipboard-write=(self "https://www.youtube-nocookie.com" "https://www.youtube.com"),
      encrypted-media=(self "https://www.youtube-nocookie.com" "https://www.youtube.com" "https://*.spotify.com"),
      fullscreen=(),
      geolocation=(),
      gyroscope=(self "https://www.youtube-nocookie.com" "https://www.youtube.com"),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(self "https://www.youtube-nocookie.com" "https://www.youtube.com"),
      speaker=(),
      usb=(),
      vibrate=(),
      vr=()
  '''